const events = {
  "01-01": ["New Year’s Day"],
  "01-02": ["World Introvert Day"],
  "01-03": ["Festival of Sleep Day"],
  "01-04": ["World Braille Day (UN)"],
  "01-05": ["National Bird Day (US, but recognised online)"],
  "01-06": ["Epiphany / Three Kings’ Day"],
  "01-07": ["Orthodox Christmas Day"],
  "01-08": ["Elvis Presley’s Birthday (celebrated globally)"],
  "01-09": ["International Choreographers Day"],
  "01-10": ["World Hindi Day"],
  "01-11": ["International Thank You Day"],
  "01-12": ["National Youth Day (India, but international mention)"],
  "01-13": ["Korean-American Day"],
  "01-14": ["Orthodox New Year"],
  "01-15": ["Martin Luther King Jr. Day (US, 2025 date)"],
  "01-16": ["International Hot & Spicy Food Day"],
  "01-17": ["Benjamin Franklin Day"],
  "01-18": ["Winnie the Pooh Day"],
  "01-19": ["World Quark Day (food day, but real!)"],
  "01-20": ["Penguin Awareness Day"],
  "01-21": ["World Religion Day"],
  "01-22": ["Celebration of Life Day"],
  "01-23": ["National Handwriting Day"],
  "01-24": ["International Day of Education (UN)"],
  "01-25": ["Burns Night (Scotland)"],
  "01-26": ["Australia Day / Republic Day (India)"],
  "01-27": ["International Holocaust Remembrance Day (UN)"],
  "01-28": ["Data Privacy Day"],
  "01-29": ["Puzzle Day"],
  "01-30": ["Croissant Day"],
  "01-31": ["Inspire Your Heart with Art Day"],
  "02-01": ["World Hijab Day", "National Freedom Day (US)"],
  "02-02": ["World Wetlands Day"],
  "02-03": ["National Day of Unplugging", "Setsubun (Japan)"],
  "02-04": ["World Cancer Day"],
  "02-05": ["International Day of Zero Tolerance for Female Genital Mutilation"],
  "02-06": ["International Day of Women and Girls in Science"],
  "02-07": ["Safer Internet Day"],
  "02-08": ["World Pangolin Day"],
  "02-09": ["Pizza Day (fun/pop culture)"],
  "02-10": ["World Pulses Day"],
  "02-11": ["International Day of Women and Girls in Science"],
  "02-12": ["Darwin Day", "Chinese New Year (variable)"],
  "02-13": ["World Radio Day"],
  "02-14": ["Valentine’s Day", "World Donor Day (some)"],
  "02-15": ["International Childhood Cancer Day"],
  "02-16": ["Innovation Day"],
  "02-17": ["Random Acts of Kindness Day"],
  "02-18": ["National Drink Wine Day (popular)"],
  "02-19": ["Global Whale Day"],
  "02-20": ["World Day of Social Justice"],
  "02-21": ["International Mother Language Day"],
  "02-22": ["World Thinking Day"],
  "02-23": ["International Dog Biscuit Day (fun)"],
  "02-24": ["World Bartender Day", "National Tortilla Chip Day"],
  "02-25": ["International Stand Up to Bullying Day"],
  "02-26": ["World Pistachio Day", "Levi Strauss Day"],
  "02-27": ["International Polar Bear Day"],
  "02-28": ["Rare Disease Day"],
  "02-29": ["Rare Disease Day"],
  "03-01": ["Zero Discrimination Day", "World Seagrass Day"],
  "03-02": ["Read Across America Day (Dr. Seuss Day)"],
  "03-03": ["World Wildlife Day", "World Hearing Day"],
  "03-04": ["World Obesity Day"],
  "03-05": ["International Day for the Elimination of Racial Discrimination"],
  "03-06": ["European Day of the Righteous"],
  "03-07": ["World Maths Day"],
  "03-08": ["International Women’s Day"],
  "03-09": ["Commonwealth Day (variable)"],
  "03-10": ["International Day of Women Judges"],
  "03-11": ["World Kidney Day"],
  "03-12": ["Plant a Flower Day"],
  "03-13": ["World Sleep Day (variable)"],
  "03-14": ["Pi Day", "International Day of Action for Rivers"],
  "03-15": ["World Consumer Rights Day", "World Sleep Day (occasionally)"],
  "03-16": ["World Sleep Day (if not 13)", "National Freedom of Information Day"],
  "03-17": ["St. Patrick’s Day"],
  "03-18": ["Global Recycling Day"],
  "03-19": ["World Sleep Day (if date shifts)", "Social Justice Day"],
  "03-20": ["International Day of Happiness", "World Sparrow Day"],
  "03-21": ["World Poetry Day", "International Day to Eliminate Racial Discrimination", "International Day of Forests"],
  "03-22": ["World Water Day"],
  "03-23": ["World Meteorological Day"],
  "03-24": ["World Tuberculosis Day"],
  "03-25": ["International Day of Remembrance of the Victims of Slavery"],
  "03-26": ["Purple Day (for epilepsy awareness)"],
  "03-27": ["World Theatre Day"],
  "03-28": ["Respect Your Cat Day (fun)"],
  "03-29": ["Palm Sunday (variable)"],
  "03-30": ["International Day of Zero Waste"],
  "03-31": ["International Transgender Day of Visibility"],
  "04-01": ["April Fools’ Day", "International Fun at Work Day"],
  "04-02": ["World Autism Awareness Day", "International Children’s Book Day"],
  "04-03": ["National Burrito Day"],
  "04-04": ["International Day for Mine Awareness and Assistance in Mine Action"],
  "04-05": ["International Day of Conscience"],
  "04-06": ["International Day of Sport for Development and Peace"],
  "04-07": ["World Health Day (WHO/UN)"],
  "04-08": ["International Romani Day"],
  "04-09": ["No excuses today. Womp womp"],
  "04-10": ["Siblings Day"],
  "04-11": ["National Living Donor Day"],
  "04-12": ["International Day of Human Space Flight (UN)"],
  "04-13": ["Songkran (Thai New Year — date varies regionally)"],
  "04-14": ["Vaisakhi (Sikh New Year / harvest festival; regional)"],
  "04-15": ["World Art Day"],
  "04-16": ["No excuses today. Womp womp"],
  "04-17": ["No excuses today. Womp womp"],
  "04-18": ["International Day for Monuments and Sites (World Heritage Day)"],
  "04-19": ["No excuses today. Womp womp"],
  "04-20": ["No excuses today. Womp womp"],
  "04-21": ["World Creativity & Innovation Day (UN)"],
  "04-22": ["Earth Day"],
  "04-23": ["World Book Day", "English (Shakespeare) Day"],
  "04-24": ["World Immunization Week"],
  "04-25": ["World Malaria Day"],
  "04-26": ["World Intellectual Property Day"],
  "04-27": ["No excuses today. Womp womp"],
  "04-28": ["World Day for Safety and Health at Work"],
  "04-29": ["International Day in Memory of the Victims of Earthquakes (UN)"],
  "04-30": ["International Jazz Day"],
  "05-01": ["International Workers’ Day", "Labour Day (global)"],
  "05-02": ["World Tuna Day (UN)"],
  "05-03": ["World Press Freedom Day (UN)"],
  "05-04": ["Star Wars Day ('May the 4th be with you')"],
  "05-05": ["Cinco de Mayo", "International Day of the Midwife"],
  "05-06": ["International No Diet Day"],
  "05-07": ["World Asthma Day (1st Tuesday in May 2025)"],
  "05-08": ["World Red Cross and Red Crescent Day"],
  "05-09": ["Europe Day (EU)"],
  "05-10": ["World Lupus Day"],
  "05-11": ["Mother’s Day (2nd Sunday in May 2025)"],
  "05-12": ["International Nurses Day"],
  "05-13": ["World Cocktail Day"],
  "05-14": ["No excuses today. Womp womp"],
  "05-15": ["International Day of Families (UN)"],
  "05-16": ["International Day of Light (UNESCO)"],
  "05-17": ["International Day Against Homophobia, Biphobia, and Transphobia"],
  "05-18": ["International Museum Day"],
  "05-19": ["World Family Doctor Day"],
  "05-20": ["World Bee Day (UN)", "World Metrology Day"],
  "05-21": ["World Day for Cultural Diversity for Dialogue and Development"],
  "05-22": ["International Day for Biological Diversity"],
  "05-23": ["World Turtle Day"],
  "05-24": ["Commonwealth Day (variable)"],
  "05-25": ["Africa Day (observed in AU/UN frameworks)"],
  "05-26": ["No excuses today. Womp womp"],
  "05-27": ["No excuses today. Womp womp"],
  "05-28": ["World MS Day (2025)"],
  "05-29": ["International Day of UN Peacekeepers"],
  "05-30": ["World Multiple Sclerosis Day (alternate calendars fix at 30)"],
  "05-31": ["World No Tobacco Day (WHO/UN)"],
  "06-01": ["Global Day of Parents (UN)", "International Children’s Day"],
  "06-02": ["International Sex Workers’ Day"],
  "06-03": ["World Bicycle Day (UN)"],
  "06-04": ["International Day of Innocent Children Victims of Aggression (UN)"],
  "06-05": ["World Environment Day (UNEP/UN)"],
  "06-06": ["D-Day Anniversary (WWII)"],
  "06-07": ["World Food Safety Day (UN)"],
  "06-08": ["World Oceans Day (UN)"],
  "06-09": ["International Archives Day"],
  "06-10": ["Portugal Day (Dia de Camões, Portugal & Communities)"],
  "06-11": ["King Kamehameha Day (Hawai‘i)"],
  "06-12": ["World Day Against Child Labour (UN)", "Russia Day"],
  "06-13": ["International Albinism Awareness Day (UN)"],
  "06-14": ["World Blood Donor Day (WHO)", "Flag Day (US)"],
  "06-15": ["World Elder Abuse Awareness Day (UN)"],
  "06-16": ["International Day of the African Child"],
  "06-17": ["World Day to Combat Desertification and Drought (UN)", "Icelandic National Day"],
  "06-18": ["Autistic Pride Day", "International Picnic Day"],
  "06-19": ["Juneteenth (US federal holiday)"],
  "06-20": ["World Refugee Day (UN)"],
  "06-21": ["International Day of Yoga (UN)", "Summer Solstice", "World Music Day"],
  "06-22": ["World Rainforest Day"],
  "06-23": ["United Nations Public Service Day", "International Widows’ Day"],
  "06-24": ["Inti Raymi (Incan Festival of the Sun, Peru)", "St John’s Day (Europe/Latin America)"],
  "06-25": ["Croatia Statehood Day", "Mozambique Independence Day"],
  "06-26": ["International Day Against Drug Abuse and Illicit Trafficking (UN)", "International Day in Support of Victims of Torture (UN)"],
  "06-27": ["Micro-, Small and Medium-sized Enterprises Day (UN)", "National HIV Testing Day (US)"],
  "06-28": ["Stonewall Riots Anniversary"],
  "06-29": ["International Day of the Tropics (UN)", "St Peter and Paul Feast Day (Christian)"],
  "06-30": ["International Asteroid Day (UN)", "Social Media Day"],
  "07-01": ["International Joke Day", "Canada Day", "Rwanda Independence Day"],
  "07-02": ["World UFO Day", "Bahia Independence Day (Brazil)"],
  "07-03": ["Belarus Independence Day"],
  "07-04": ["US Independence Day"],
  "07-05": ["Algeria Independence Day", "Venezuela Independence Day"],
  "07-06": ["International Kissing Day", "Malawi Independence Day"],
  "07-07": ["World Chocolate Day", "Solomon Islands Independence Day"],
  "07-08": ["South Sudan Independence Day (2011)"],
  "07-09": ["Argentina Independence Day"],
  "07-10": ["Bahamas Independence Day"],
  "07-11": ["World Population Day (UN)", "Mongolia Naadam Festival begins"],
  "07-12": ["Orangemen’s Day (Northern Ireland)", "Kiribati Independence Day"],
  "07-13": ["Montenegro Statehood Day"],
  "07-14": ["Bastille Day (France)"],
  "07-15": ["Brunei Sultan’s Birthday"],
  "07-16": ["Our Lady of Mount Carmel Feast Day"],
  "07-17": ["World Emoji Day", "South Korea Constitution Day"],
  "07-18": ["Nelson Mandela International Day (UN)"],
  "07-19": ["Sandinista Revolution Day (Nicaragua)"],
  "07-20": ["Colombia Independence Day"],
  "07-21": ["Belgium National Day"],
  "07-22": ["Pi Approximation Day", "Ratcatcher’s Day (Germany)"],
  "07-23": ["Egypt Revolution Day (1952)"],
  "07-24": ["Simón Bolívar Day (Latin America)"],
  "07-25": ["St James’ Day", "Puerto Rico Constitution Day"],
  "07-26": ["Liberia Independence Day", "Maldives Independence Day"],
  "07-27": ["National Sleepy Head Day (Finland)", "Peru Independence Eve"],
  "07-28": ["Peru Independence Day"],
  "07-29": ["International Tiger Day"],
  "07-30": ["International Day of Friendship (UN)", "Vanuatu Independence Day"],
  "07-31": ["Feast of St Ignatius of Loyola"],
  "08-01": ["Switzerland National Day", "Benin Independence Day"],
  "08-02": ["Republic Day (North Macedonia)", "Our Lady of the Angels Day (Costa Rica)"],
  "08-03": ["Niger Independence Day"],
  "08-04": ["Burkina Faso Independence Day"],
  "08-05": ["Burkina Faso Revolution Day", "Upper Volta Day", "Burkina Faso Independence Day"],
  "08-06": ["Jamaica Independence Day", "Bolivia Independence Day", "Hiroshima Peace Memorial Day"],
  "08-07": ["Ivory Coast Independence Day"],
  "08-08": ["International Cat Day"],
  "08-09": ["International Day of the World’s Indigenous Peoples (UN)", "Singapore National Day"],
  "08-10": ["Ecuador Independence Day"],
  "08-11": ["Chad Independence Day"],
  "08-12": ["International Youth Day (UN)"],
  "08-13": ["Left-Handers Day", "Central African Republic Independence Day"],
  "08-14": ["Pakistan Independence Day"],
  "08-15": ["India Independence Day", "Assumption of Mary (Christian feast)", "Congo Independence Day (Republic of Congo)"],
  "08-16": ["Bennington Battle Day (Vermont, US)", "Gabon Independence Day"],
  "08-17": ["Indonesia Independence Day"],
  "08-18": ["Vietnam Revolution Day"],
  "08-19": ["World Humanitarian Day (UN)", "Afghanistan Independence Day"],
  "08-20": ["Hungary St Stephen’s Day", "World Mosquito Day"],
  "08-21": ["Ninoy Aquino Day (Philippines)"],
  "08-22": ["International Day Commemorating Victims of Acts of Violence Based on Religion or Belief (UN)", "Madras Day (India)"],
  "08-23": ["International Day for the Remembrance of the Slave Trade and its Abolition (UNESCO)"],
  "08-24": ["Ukraine Independence Day"],
  "08-25": ["Uruguay Independence Day"],
  "08-26": ["Women’s Equality Day (US)"],
  "08-27": ["Moldova Independence Day"],
  "08-28": ["Feast of St Augustine", "Martin Luther King Jr.’s “I Have a Dream” Speech Anniversary"],
  "08-29": ["International Day against Nuclear Tests (UN)", "Slovakia National Uprising Day"],
  "08-30": ["International Day of the Victims of Enforced Disappearances (UN)", "Turkey Victory Day"],
  "08-31": ["Malaysia Independence Day (Hari Merdeka)", "Trinidad and Tobago Independence Day", "Kyrgyzstan Independence Day"],
  "09-01": ["Slovak Constitution Day", "Uzbekistan Independence Day", "Libya Revolution Day"],
  "09-02": ["Vietnam National Day"],
  "09-03": ["San Marino Foundation Day", "Qatar Independence Day (1971)"],
  "09-04": ["Newspaper Carrier Day (US)"],
  "09-05": ["International Day of Charity (UN)"],
  "09-06": ["Swaziland (Eswatini) Independence Day"],
  "09-07": ["Brazil Independence Day"],
  "09-08": ["International Literacy Day (UNESCO)", "North Macedonia Independence Day", "Andorra National Day"],
  "09-09": ["North Korea National Day", "Tajikistan Independence Day"],
  "09-10": ["World Suicide Prevention Day"],
  "09-11": ["Catalonia National Day", "Patriot Day (US)"],
  "09-12": ["United Nations Day for South-South Cooperation", "Ethiopia New Year (Enkutatash)"],
  "09-13": ["Programmer’s Day", "Positive Thinking Day"],
  "09-14": ["Holy Cross Day (Christian feast)"],
  "09-15": ["International Day of Democracy (UN)", "Independence Day: Honduras, El Salvador, Guatemala, Nicaragua, Costa Rica"],
  "09-16": ["Mexico Independence Day", "Papua New Guinea Independence Day"],
  "09-17": ["Constitution Day (US)", "Teachers’ Day (Honduras)"],
  "09-18": ["Chile Independence Day"],
  "09-19": ["International Talk Like a Pirate Day", "Saint Kitts and Nevis Independence Day"],
  "09-20": ["National Youth Day (Thailand)"],
  "09-21": ["International Day of Peace (UN)", "Malta Independence Day", "Armenia Independence Day", "Belize Independence Day"],
  "09-22": ["Mali Independence Day", "Hobbit Day"],
  "09-23": ["Saudi National Day", "Bi Visibility Day", "Autumn Equinox (variable)"],
  "09-24": ["Guinea-Bissau Independence Day", "South Africa Heritage Day"],
  "09-25": ["World Pharmacists Day (FIP)", "Mozambique Armed Forces Day"],
  "09-26": ["European Day of Languages", "New Zealand Dominion Day"],
  "09-27": ["World Tourism Day (UNWTO)"],
  "09-28": ["International Day for Universal Access to Information (UNESCO)", "Czech Statehood Day"],
  "09-29": ["World Heart Day (WHO)", "Michaelmas (Christian feast)"],
  "09-30": ["International Translation Day (UN)", "Botswana Independence Day"],
  "10-01": ["International Day of Older Persons (UN)", "Nigeria Independence Day", "China National Day"],
  "10-02": ["International Day of Non-Violence (UN)", "Gandhi Jayanti (India)"],
  "10-03": ["German Unity Day"],
  "10-04": ["World Animal Day", "Feast of St Francis of Assisi"],
  "10-05": ["World Teachers’ Day (UNESCO)"],
  "10-06": ["German-American Day (US)", "Armed Forces Day (Egypt)"],
  "10-07": ["World Cotton Day (UN)"],
  "10-08": ["Croatian Independence Day"],
  "10-09": ["World Post Day (UN)", "Uganda Independence Day", "Hangul Day (Korea)"],
  "10-10": ["World Mental Health Day (WHO)"],
  "10-11": ["International Day of the Girl Child (UN)", "National Coming Out Day"],
  "10-12": ["Día de la Raza (Latin America)", "Spain National Day", "Indigenous Peoples’ Day (US)"],
  "10-13": ["International Day for Disaster Reduction (UN)"],
  "10-14": ["World Standards Day"],
  "10-15": ["Global Handwashing Day", "International Day of Rural Women (UN)"],
  "10-16": ["World Food Day (UN FAO)"],
  "10-17": ["International Day for the Eradication of Poverty (UN)"],
  "10-18": ["Azerbaijan Independence Day", "World Menopause Day"],
  "10-19": ["Evaluate Your Life Day"],
  "10-20": ["World Statistics Day (every 5 years, next 2025)", "Kenya Mashujaa Day"],
  "10-21": ["Trafalgar Day (UK)"],
  "10-22": ["International Stuttering Awareness Day"],
  "10-23": ["Mole Day", "Hungarian Revolution Day"],
  "10-24": ["United Nations Day", "World Development Information Day"],
  "10-25": ["World Pasta Day", "Republic Day (Kazakhstan)"],
  "10-26": ["Austria National Day"],
  "10-27": ["World Day for Audiovisual Heritage (UNESCO)"],
  "10-28": ["Czech Republic Independence Day", "Ohi Day (Greece)"],
  "10-29": ["Turkey Republic Day"],
  "10-30": ["Mischief Night (US/UK)"],
  "10-31": ["Halloween", "Reformation Day (Protestant churches)"],
  "11-01": ["All Saints’ Day (Christian)", "Día de los Muertos (Mexico, Day 1)"],
  "11-02": ["All Souls’ Day (Christian)", "Día de los Muertos (Mexico, Day 2)"],
  "11-03": ["Panama Independence Day", "Dominica Independence Day", "Culture Day (Japan)"],
  "11-04": ["Russia Unity Day"],
  "11-05": ["Guy Fawkes Night (UK)"],
  "11-06": ["International Day for Preventing the Exploitation of the Environment in War and Armed Conflict (UN)"],
  "11-07": ["October Revolution Day (historical, Russia)", "Infant Protection Day"],
  "11-08": ["World Urbanism Day (World Town Planning Day)"],
  "11-09": ["World Freedom Day (US)", "Cambodia Independence Day", "Fall of the Berlin Wall Anniversary"],
  "11-10": ["World Science Day for Peace and Development (UNESCO)"],
  "11-11": ["Armistice Day", "Veterans Day (US)", "Remembrance Day (Commonwealth)"],
  "11-12": ["World Pneumonia Day", "Diwali (in some years)"],
  "11-13": ["World Kindness Day"],
  "11-14": ["World Diabetes Day (WHO)", "Children’s Day (India)"],
  "11-15": ["Brazil Republic Day", "National Tree Planting Day (Sri Lanka)"],
  "11-16": ["International Day for Tolerance (UNESCO)"],
  "11-17": ["International Students’ Day", "Czech Struggle for Freedom and Democracy Day"],
  "11-18": ["Latvia Independence Day", "Oman National Day"],
  "11-19": ["International Men’s Day", "World Toilet Day (UN)", "Monaco National Day"],
  "11-20": ["Universal Children’s Day (UN)", "Africa Industrialisation Day (UN)"],
  "11-21": ["World Television Day (UN)", "World Hello Day"],
  "11-22": ["Lebanon Independence Day"],
  "11-23": ["St George’s Day (Georgia)", "Thanksgiving (US, 2025)"],
  "11-24": ["Evolution Day (Darwin’s Origin of Species)"],
  "11-25": ["International Day for the Elimination of Violence Against Women (UN)"],
  "11-26": ["Constitution Day (India)"],
  "11-27": ["Maaveerar Naal (Tamil Remembrance Day)"],
  "11-28": ["Albania Independence Day", "Mauritania Independence Day"],
  "11-29": ["International Day of Solidarity with the Palestinian People (UN)"],
  "11-30": ["St Andrew’s Day (Scotland)", "Barbados Independence Day"],
  "12-01": ["World AIDS Day (UN)", "Romania National Day"],
  "12-02": ["International Day for the Abolition of Slavery (UN)", "Laos National Day", "UAE National Day"],
  "12-03": ["International Day of Persons with Disabilities (UN)"],
  "12-04": ["International Cheetah Day", "Navy Day (India)"],
  "12-05": ["International Volunteer Day (UN)", "World Soil Day (UN FAO)", "Thailand King’s Birthday"],
  "12-06": ["St Nicholas Day", "Finland Independence Day"],
  "12-07": ["International Civil Aviation Day (UN)", "Pearl Harbor Remembrance Day (US)"],
  "12-08": ["Feast of the Immaculate Conception (Catholic)"],
  "12-09": ["International Anti-Corruption Day (UN)", "Tanzania Independence Day"],
  "12-10": ["Human Rights Day (UN)", "Nobel Prize Day"],
  "12-11": ["International Mountain Day (UN)"],
  "12-12": ["Kenya Independence Day", "Feast of Our Lady of Guadalupe (Mexico)"],
  "12-13": ["St Lucy’s Day (Sweden/Scandinavia)"],
  "12-14": ["Monkey Day"],
  "12-15": ["Bill of Rights Day (US)"],
  "12-16": ["Bahrain National Day", "South Africa Day of Reconciliation", "Kazakhstan Independence Day"],
  "12-17": ["Bhutan National Day", "Wright Brothers Day (US)"],
  "12-18": ["International Migrants Day (UN)", "Qatar National Day"],
  "12-19": ["UN Resolution Day"],
  "12-20": ["International Human Solidarity Day (UN)"],
  "12-21": ["Winter Solstice (Northern Hemisphere)", "Yule (Pagan tradition)"],
  "12-22": ["Forefathers’ Day (US)"],
  "12-23": ["Festivus (pop culture holiday)"],
  "12-24": ["Christmas Eve (Christian)"],
  "12-25": ["Christmas Day (Christian, global holiday)"],
  "12-26": ["Boxing Day (Commonwealth)", "Kwanzaa (Day 1, US)"],
  "12-27": ["St John the Apostle’s Day"],
  "12-28": ["Holy Innocents’ Day (Christian)"],
  "12-29": ["Constitution Day (Ireland)", "Wounded Knee Massacre Remembrance"],
  "12-30": ["Rizal Day (Philippines)"],
  "12-31": ["New Year’s Eve 🎆"]
}